name: Elixir CI

on: ["push", "pull_request"]

jobs:
  check-commit-message:
    name: check commit message for skipping build(s)
    runs-on: ubuntu-latest

    # skips CI and prints cli message, without fail build badge
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: print message via cli
        run: echo "no need to build, based from commit message"

  setup-elixir:
    name: Setup Elixir and test it
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # doesn't contain "ci skip" in commit message
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.9

      - name: get deps cache
        uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps/
          key: ${{ runner.os }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-deps-

      - name: get build cache
        uses: actions/cache@v1
        id: build-cache
        with:
          path: _build/test/
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install Dependencies
        if: (steps.deps-cache.outputs.cache-hit != 'true') && (steps.build-cache.outputs.cache-hit != 'true')
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix format --check-formatted

      - name: Run Tests
        run: mix test

